source 'https://api.berkshelf.com'

#cookbook 'apache2'
cookbook 'jenkins'
cookbook 'jenkins-configuration', :path => './site-cookbooks/jenkins-configuration'

#cookbook 'rvm', github: 'fnichol/chef-rvm'
#cookbook 'python'
#cookbook 'firefox'
#cookbook 'magic_shell'
#cookbook 'yum'