source 'https://api.berkshelf.com'

cookbook 'jenkins'
cookbook 'jenkins-configuration', :path => './site-cookbooks/jenkins-configuration'
cookbook 'apache-configuration', :path => './site-cookbooks/apache-configuration'