# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'ubuntu/trusty64'

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network 'forwarded_port', guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network 'private_network', ip: '192.168.33.10'

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  config.ssh.forward_agent = true

  config.vm.provision 'chef_solo' do |chef|
    cookbooks_path = []

    %w{jenkins::master}.each { |recipe| chef.add_recipe recipe }

    # You may also specify custom JSON attributes:
    chef.json = {
      jenkins: {
        #notifications: {
        #  enabled: 'false'
        #},
        #http_proxy: {
        #  variant: 'apache2'
        #},
        #server: {
        #  plugins: JSON.parse(IO.read('plugins.json'))
        #},

        install_method: 'package',
        version: '1.567-1.1'
      }
    }
  end
end
